baseurl = "https://www.nerdseverino.com.br/"
# Shown in the side menu
copyright = "&copy; 2020. All rights reserved."
canonifyurls = true
paginate = 10
theme = "hyde-x"
disqusShortname = "https-nerdseverino-com-br"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[author]
    name = "Fabrício Machado"
    tagline = "Compartilhar o conhecimento é multiplicar o seu próprio!"
    homepage = "https://www.nerdseverino.com.br"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:year/:month/:day/:title"

[taxonomies]
  tag = "tags"
  topic = "categories"

[params]
  # Shown in the home page
  truncate = true
  defaultDescription = "Dedicado a trazer informações sobre software e tecnologias da atualidade e coisas do Cotidiano."
  hideReadingTime = false
  theme = "theme-base-0f"
  googleAnalytics = ""
  home = "Home"
  github = "https://github.com/nerdseverino"
  bitbucket = ""
  stackOverflow = ""
  linkedin = "https://www.linkedin.com/in/fabriciomachado/"
  googleplus = "https://t.me/systemcrashpoa"
  facebook = ""
  twitter = "https://twitter.com/tuxsabe"
  youtube = ""

  [menu]
    # Shown in the side menu.
    [[menu.main]]
      name = "Home"
      pre = "<i class='fa fa-home fa-fw'></i>"
      weight = 0
      identifier = "home"
      url = "/tags/portugues"
    [[menu.main]]
      name = "Portuguese"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 1
      identifier = "portuguese"
      url = "/tags/portugues"
    [[menu.main]]
      name = "English"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 2
      identifier = "english"
      url = "/tags/english"
    [[menu.main]]
      name = "About"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 3
      identifier = "about"
      url = "/about/"
    [[menu.main]]
      name = "RSS"
      pre = "<i class='fa fa-rss fa-fw'></i>"
      weight = 3
      identifier = "rss"
      url = "/index.xml"


  #  [[menu.main]]
  #    name = "Contact"
  #    pre = "<i class='fa fa-phone fa-fw'></i>"
  #    weight = 3
  #    url = "/contact/"
  #
   
