baseurl = "https://www.nerdseverino.com.br/"
#title = "Fabrício Data Memories :D"
#author = "Fabrício Machado"
# Shown in the side menu
copyright = "&copy; 2020. All rights reserved."
canonifyurls = true
paginate = 10
theme = "hyde-x"
disqusShortname = ""
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
#---------------------------------------------------
backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master
  site_url: https://www.nerdseverino.com.br
#  logo_url: https://res.cloudinary.com/iambeejayayo/image/upload/v1547954566/fav-500.png

publish_mode: editorial_workflow

media_folder: "img/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "article" # Used in the UI
    folder: "/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "post", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "array"}
      - {label: "Body", name: "body", widget: "markdown"}     

#---------------------------------------------------

[author]
    name = "Fabrício Machado"
    homepage = "https://www.nerdseverino.com.br"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:year/:month/:day/:title"

[taxonomies]
  tag = "tags"
  topic = "categories"

[params]
  # Shown in the home page
  truncate = true
  defaultDescription = "The bytes of universe inside in a nutshell"
  hideReadingTime = false
  theme = "theme-base-09"
  googleAnalytics = "UA-34467089-1"
  home = "Home"
  github = "https://github.com/nerdseverino"
  bitbucket = ""
  stackOverflow = ""
  linkedin = "https://www.linkedin.com/in/fabriciomachado/"
  googleplus = ""
  facebook = ""
  twitter = "https://twitter.com/tuxsabe"
  youtube = ""

  [menu]
    # Shown in the side menu.
    [[menu.main]]
      name = "Home"
      pre = "<i class='fa fa-home fa-fw'></i>"
      weight = 0
      identifier = "home"
      url = "/tags/portugues"
    [[menu.main]]
      name = "Portuguese"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 1
      identifier = "portuguese"
      url = "https://www.nerdseverino.com.br/tags/portugues"
    [[menu.main]]
      name = "English"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 2
      identifier = "english"
      url = "https://www.nerdseverino.com.br/tags/english"
    [[menu.main]]
      name = "About"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 3
      identifier = "about"
      url = "/about/"


  #  [[menu.main]]
  #    name = "Contact"
  #    pre = "<i class='fa fa-phone fa-fw'></i>"
  #    weight = 3
  #    url = "/contact/"
  #
   
