[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.1"



[context.production.environment]
   HUGO_VERSION = "0.63.1"

[build]
  command = "npm run build"

# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "src/_data"

    # All the feeds we wish to gather for use in the build
    [[plugins.inputs.feeds]]
      name = "Nerd Severino Feed"
      url = "http://nerdseverino.com.br/feed.json"
      ttl = 120
    [[plugins.inputs.feeds]]
      name = "Nerd Severino Feed"
      url = "https://www.nerdseverino.com.br/index.xml"
      ttl = 86400
