[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.1"



[context.production.environment]
   HUGO_VERSION = "0.63.1"

# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "src/_data"

    [[plugins.inputs.feeds]]
      name = "nerdseverinofeed"
      url = "http://nerdseverino.com.br/feed.json"
      ttl = 3600

    [[plugins.inputs.feeds]]
      name = "NerdSeverinoFeed"
      url = "https://www.nerdseverino.com.br/index.xml"
      ttl = 86400
